In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
df = pd.read_csv("american.csv")

In [8]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [10]:
x

array([[553.0, 'Delhi', 0, ..., 4.0, 1.0, 274150.0],
       [447.0, 'Bengaluru', 1, ..., 4.0, 1.0, 519360.0],
       [501.0, 'Delhi', 0, ..., 4.0, 1.0, 545501.0],
       ...,
       [600.0, 'Bengaluru', 0, ..., 2.0, 1.0, 109375.0],
       [553.0, 'Delhi', 1, ..., 4.0, 1.0, 180031.0],
       [nan, nan, 2, ..., nan, nan, nan]], dtype=object)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [1.0 0.0 0.0 ... 2.0 1.0 109375.0]
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]
 [0.0 0.0 0.0 ... nan nan nan]]


In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [34]:
ann = tf.keras.models.Sequential()

In [35]:
ann.add(tf.keras.layers.Dense(units = 5,activation = 'relu' ))#input

In [36]:
ann.add(tf.keras.layers.Dense(units = 5,activation = 'relu' ))#hidden layer

In [59]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid' ))

In [38]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [61]:
ann.fit(x_train, y_train, batch_size=32, epochs=120)

Epoch 1/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3844 - accuracy: 0.8315
Epoch 2/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3838 - accuracy: 0.8316
Epoch 3/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3832 - accuracy: 0.8326
Epoch 4/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3831 - accuracy: 0.8314
Epoch 5/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3825 - accuracy: 0.8316
Epoch 6/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3822 - accuracy: 0.8330
Epoch 7/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3818 - accuracy: 0.8325
Epoch 8/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3817 - accuracy: 0.8329
Epoch 9/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3814 - accuracy: 0.8326
Epoch 10/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3810 - accura

In [62]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 987us/step


In [64]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
cm
accuracy_score(y_test,y_pred)

0.851460221550856